### 1. Importing necessary libraries

In [6]:
import numpy as np
import copy

### 2. Sudoku class to implement the sudoku game

In [7]:
class Sudoku:
    def __init__(self,board):
        self.board = board
        self.done = False                                        
    def check_move(self,position,number):
        """Function to check whether inserting number into board at particular position is allowed
        """
        x,y = position
        seg_x = int(x/3)
        seg_y = int(y/3)
        if self.board[x,y]!=0:
            return False
        for i in range(9):
            if i!=y and self.board[x,i] == number:
                return False
        for i in range(9):
            if i!=x and self.board[i,y] == number:
                return False
        for i in range(9):
            for j in range(9):
                if seg_x==int(i/3) and seg_y==int(j/3) and i!=x and j!=y and self.board[i,j]==number:
                    return False
        return True
    def move(self,position,number):
        """Function that allows player to insert number into an empty position in the board"""
        if self.check_move(position,number) == True:
            self.board[position[0],position[1]] = number
    def display_board(self):
        """
        Function to display game board itself as 2D numpy array
        """
        print(self.board)
    def find_empty_position(self,empty):
        """Function to find first empty postion (used as helper function in abcktracking algorithm)"""
        for i in range(9):
            for j in range(9):
                if self.board[i,j]==0:
                    empty[0]= i
                    empty[1] =j
                    return True
        
        return False
    def solve(self):
        """Implementation of backtracking to solve the sudoku board """
        empty = [0,0]
        
        if self.find_empty_position(empty)==False:     
           return True      #Terminate successfully if no more empty positions left to be filled
           
        x = empty[0]
        y = empty[1]
        
        for i in range (1,10):
           if self.check_move((x,y),i)==True:           
                self.board[x,y] = i      #True if current empty position can be filled with any number
                
                if (self.solve()):      #recursive call to solve rest of the board
                    return True
                self.board[x,y]=0
        return False                    #if no number colud be inserted return False (backtrack)

### 3. Creating hard level sudoku puzzle question

In [8]:
#hard
board = np.zeros((9,9))
board[0,6] = 2
board[1,1]= 8
board[1,5]= 7
board[1,7]= 9
board[2,0]= 6
board[2,2]= 2
board[2,6]= 5
board[3,1]= 7
board[3,4]= 6
board[4,3]= 9
board[4,5]= 1
board[5,4]= 2
board[5,7]=4
board[6,2]=5
board[6,6]=6
board[6,8]=3
board[7,1]=9
board[7,3]=4
board[7,7]=7
board[8,2]=6
game = Sudoku(copy.deepcopy(board))
print("Unsolved 9x9 Board :\n")
game.display_board()

Unsolved 9x9 Board :

[[0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 8. 0. 0. 0. 7. 0. 9. 0.]
 [6. 0. 2. 0. 0. 0. 5. 0. 0.]
 [0. 7. 0. 0. 6. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 4. 0.]
 [0. 0. 5. 0. 0. 0. 6. 0. 3.]
 [0. 9. 0. 4. 0. 0. 0. 7. 0.]
 [0. 0. 6. 0. 0. 0. 0. 0. 0.]]


### 4.Using Backtracking algorithm to solve the game

In [9]:
game.solve()

True

### 5. Diplaying solved 9x9 board

In [10]:
print("Solved 9x9 Board :\n")
game.display_board()

Solved 9x9 Board :

[[9. 5. 7. 6. 1. 3. 2. 8. 4.]
 [4. 8. 3. 2. 5. 7. 1. 9. 6.]
 [6. 1. 2. 8. 4. 9. 5. 3. 7.]
 [1. 7. 8. 3. 6. 4. 9. 5. 2.]
 [5. 2. 4. 9. 7. 1. 3. 6. 8.]
 [3. 6. 9. 5. 2. 8. 7. 4. 1.]
 [8. 4. 5. 7. 9. 2. 6. 1. 3.]
 [2. 9. 1. 4. 3. 6. 8. 7. 5.]
 [7. 3. 6. 1. 8. 5. 4. 2. 9.]]
